name: Build & Push Docker Image

on:
  push:
    branches: [ develop ]

jobs:
  build-and-push:
    runs-on: self-hosted
    needs: build-and-deploy-on-gen2--dacpac.yml   # wait on your other workflow

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'develop'

    env:
      # override these in Settings → Secrets
      PROJECT_PATH:      ${{ secrets.PROJECT_PATH }}       # e.g. src/Database/Database.sqlproj
      DACPAC_NAME:       ${{ secrets.DACPAC_NAME }}        # e.g. Database.dacpac
      REGISTRY:          ${{ secrets.DOCKER_REGISTRY }}    # e.g. registry.example.com
      IMAGE_NAME:        ${{ secrets.DOCKER_IMAGE_NAME }}  # e.g. sql-dacpac-deployer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Get SHORT_SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build & push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            PROJECT_PATH=${{ env.PROJECT_PATH }}
            DACPAC_NAME=${{ env.DACPAC_NAME }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHORT_SHA }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
