# .github/workflows/docker-build-push.yml
name: Build and Push Docker Image

# Trigger only after the "build-and-deploy-on-gen2--dacpac.yml" workflow completes
on:
  workflow_run:
    workflows:
      - build-and-deploy-on-gen2--dacpac.yml
    types:
      - completed

jobs:
  build-and-push:
    # Only run when the upstream workflow succeeded on the develop branch
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'develop'
    runs-on: self-hosted

    env:
      REGISTRY:     ${{ secrets.DOCKER_REGISTRY }}     # e.g. registry.example.com
      IMAGE_NAME:   ${{ secrets.DOCKER_IMAGE_NAME }}   # e.g. sql-deployer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short commit SHA
        id: gitvars
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Build & Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.gitvars.outputs.SHORT_SHA }}
