name: Build & Deploy SQL Database Project (with sqlpackage as a nuget tool)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]
    env:
      SQL_SERVER:   ${{ secrets.SQL_SERVER }}
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USER:     ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bootstrap .NET 8.0.404
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
      
          # install the SDK (includes runtime)
          ./dotnet-install.sh \
            --channel 8.0 \
            --version 8.0.404 \
            --install-dir $HOME/.dotnet

          # make it easy to call
          echo "export DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "export PATH=$HOME/.dotnet:$PATH" >> $GITHUB_ENV

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      # ─────────────────────────────────────────────
      # OPTION B: Dynamically find the .sqlproj file
      # ─────────────────────────────────────────────
      - name: Locate KusoDatabase.sqlproj
        id: find_sqlproj
        run: |
          SQLPROJ_PATH=$(find . -type f -name 'KusoDatabase.sqlproj' | head -n1)
          echo "Found at: $SQLPROJ_PATH"
          echo "SQLPROJ_PATH=$SQLPROJ_PATH" >> $GITHUB_ENV

      - name: Restore & build SQL project (dynamic)
        if: env.SQLPROJ_PATH != ''
        run: |
          dotnet restore "$SQLPROJ_PATH"
          dotnet build   "$SQLPROJ_PATH" \
            --configuration Release \
            /p:NetCoreBuild=true

      - name: Restore & build SQL project
        run: |
          dotnet restore ./Database/MyDatabaseProject.sqlproj
          dotnet build   ./Database/MyDatabaseProject.sqlproj \
            --configuration Release \
            /p:NetCoreBuild=true

      - name: Locate generated DACPAC
        id: find_dacpac
        run: |
          echo "DACPAC_PATH=$(find Database -type f -path '*/bin/Release/*.dacpac' | head -n1)" \
            >> $GITHUB_ENV

      - name: Install sqlpackage
        run: |
          dotnet new tool-manifest --force
          dotnet tool install Microsoft.SqlPackage --version 170.0.94
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      

      - name: Install sqlpackage as a local .NET tool
        run: |
          # initialize or overwrite tool manifest
          dotnet new tool-manifest --force
          # install the CLI from NuGet
          dotnet tool install Microsoft.SqlPackage --version 170.0.94
          # ensure the tools folder is on PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        # you can bump the version if a newer one is released :contentReference[oaicite:0]{index=0}

      - name: Deploy DACPAC to SQL Server
        run: |
          # now `sqlpackage` is on the PATH
          sqlpackage \
            /Action:Publish \
            /SourceFile:"${{ env.DACPAC_PATH }}" \
            /TargetServerName:"${{ env.SQL_SERVER }}" \
            /TargetDatabaseName:"${{ env.SQL_DATABASE }}" \
            /TargetUser:"${{ env.SQL_USER }}" \
            /TargetPassword:"${{ env.SQL_PASSWORD }}" \
            /p:DropObjectsNotInSource=True

      - name: Quick verification
        run: |
          sqlcmd \
            -S "${{ env.SQL_SERVER }}" \
            -d "${{ env.SQL_DATABASE }}" \
            -U "${{ env.SQL_USER }}" \
            -P "${{ env.SQL_PASSWORD }}" \
            -Q "SELECT COUNT(*) FROM sys.tables;"
